---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: oleksiy.pylypnko@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: gitlab-acme-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: oleksiy.pylypnko@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token