apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-server-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
