helmDefaults:
  wait: true
  timeout: 600
  waitForJobs: true

helmfiles:
  # Core systems
  - path: metallb-system/helmfile.yaml.gotmpl
  - path: secrets-system/helmfile.yaml.gotmpl

  # Networking
  - path: external-dns/helmfile.yaml.gotmpl
  - path: cert-manager/helmfile.yaml.gotmpl
  - path: ingress-nginx/helmfile.yaml.gotmpl
  - path: external-tunnel/helmfile.yaml.gotmpl

  # RBAC
  - path: rbac-system/helmfile.yaml
