apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rotation-job
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
