---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-token-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-token-generator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-token-generator-gitea-access
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-token-generator
subjects:
- kind: ServiceAccount
  name: gitea-token-generator
roleRef:
  kind: Role
  name: gitea-token-generator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-token-generator-gitea-access
subjects:
- kind: ServiceAccount
  name: gitea-token-generator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gitea-token-generator-gitea-access
  apiGroup: rbac.authorization.k8s.io
