helmfiles:
  # Core systems
  - path: metallb-system/helmfile.yaml.gotmpl
  - path: secrets-system/helmfile.yaml.gotmpl
  
  # Networking
  - path: external-dns/helmfile.yaml.gotmpl
  - path: cert-manager/helmfile.yaml.gotmpl
  - path: ingress-nginx/helmfile.yaml.gotmpl
  - path: external-tunnel/helmfile.yaml.gotmpl

  # Monitoring
  - path: victoria-metrics/helmfile.yaml.gotmpl
  
  # GitOps & CI/CD
  - path: argocd/helmfile.yaml.gotmpl
  - path: gitea/helmfile.yaml.gotmpl

  # DB
  - path: cnpg-system/helmfile.yaml.gotmpl

  # Analytics
  - path: metabase/helmfile.yaml.gotmpl
