---
- name: Configure Ceph services (catch-up mode)
  become: true
  hosts: bootstrapMaster
  tasks:
    - name: Check current hosts in cluster
      command: cephadm shell -- ceph orch host ls --format json
      register: current_hosts
      changed_when: false

    - name: Display current hosts
      debug:
        msg: "Current hosts in cluster: {{ (current_hosts.stdout | from_json) | map(attribute='hostname') | list }}"

    - name: Check current monitor placement
      command: cephadm shell -- ceph orch ls mon --format json
      register: mon_placement
      changed_when: false
      ignore_errors: true

    - name: Display current monitor services
      debug:
        var: mon_placement.stdout_lines
      when: mon_placement is defined and mon_placement.stdout_lines is defined

    - name: Apply monitor placement to all hosts
      command: >
        cephadm shell -- ceph orch apply mon --placement="blade001,blade002,blade003,blade004,blade005"
      register: mon_apply_result
      ignore_errors: true

    - name: Display monitor placement result
      debug:
        var: mon_apply_result.stdout_lines
      when: mon_apply_result is defined and mon_apply_result.stdout_lines is defined

    - name: Check current manager placement
      command: cephadm shell -- ceph orch ls mgr --format json
      register: mgr_placement
      changed_when: false
      ignore_errors: true

    - name: Display current manager services
      debug:
        var: mgr_placement.stdout_lines
      when: mgr_placement is defined and mgr_placement.stdout_lines is defined

    - name: Apply manager placement to first 3 hosts
      command: >
        cephadm shell -- ceph orch apply mgr --placement="blade001,blade002,blade003"
      register: mgr_apply_result
      ignore_errors: true

    - name: Display manager placement result
      debug:
        var: mgr_apply_result.stdout_lines
      when: mgr_apply_result is defined and mgr_apply_result.stdout_lines is defined

    - name: Wait for services to be deployed
      pause:
        seconds: 30

    - name: Display cluster status
      command: cephadm shell -- ceph status
      register: final_status

    - name: Show cluster status
      debug:
        var: final_status.stdout_lines

    - name: Display cluster health
      command: cephadm shell -- ceph health detail
      register: health_detail
      ignore_errors: yes

    - name: Show health details
      debug:
        var: health_detail.stdout_lines
      when: health_detail is defined and health_detail.stdout_lines is defined

    - name: Display installation summary
      debug:
        msg:
          - "Ceph cluster configuration completed!"
          - "Dashboard URL: https://{{ ansible_default_ipv4.address }}:8443"
          - "Username: admin"
          - "Password: admin123"
          - ""
          - "All 5 hosts should now be part of the cluster with proper service placement"
