- name: Uninstall Ceph cluster
  become: true
  hosts: all
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Stop all Ceph services
      command: systemctl stop 'ceph*'
      ignore_errors: yes

    - name: Disable all Ceph services
      command: systemctl disable 'ceph*'
      ignore_errors: yes

    - name: Remove Ceph containers
      shell: |
        docker ps -a --filter "name=ceph" --format "table {{.Names}}" | grep -v NAMES | xargs -r docker rm -f
      ignore_errors: yes

    - name: Remove Ceph images
      shell: |
        docker images --filter "reference=*ceph*" --format "table {{.Repository}}:{{.Tag}}" | grep -v REPOSITORY | xargs -r docker rmi -f
      ignore_errors: yes

    - name: Remove Ceph packages
      apt:
        name:
          - cephadm
          - ceph-common
          - ceph
          - ceph-base
          - ceph-mgr
          - ceph-mon
          - ceph-osd
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Remove Ceph directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ceph
        - /var/lib/ceph
        - /var/log/ceph
        - /opt/ceph
      ignore_errors: yes

    - name: Remove Ceph user
      user:
        name: ceph
        state: absent
        remove: yes
      ignore_errors: yes

    - name: Remove Ceph systemd units
      file:
        path: "/etc/systemd/system/{{ item }}"
        state: absent
      loop:
        - ceph.target
        - ceph-mon@.service
        - ceph-mgr@.service
        - ceph-osd@.service
      ignore_errors: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Display uninstall complete message
      debug:
        msg:
          - "Ceph uninstallation completed!"
          - "Note: Storage devices may still contain Ceph data"
          - "Use ceph-volumes runbook to clean storage devices if needed"
