apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets
  namespace: secrets
subjects:
  - kind: ServiceAccount
    name: secrets
    namespace: secrets
roleRef:
  kind: Role
  name: secrets
  apiGroup: rbac.authorization.k8s.io
