replicaCount: 1

image:
  repository: node
  pullPolicy: IfNotPresent
  tag: "18-alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 8435

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Configuration for the alertmanager-gotify bridge
config:
  # Gotify server configuration
  gotifyEndpoint: "http://gotify:8080/message"
  gotifyToken: ""
  
  # Server configuration
  listenPort: 8435
  listenAddr: "0.0.0.0"
  
  # Default values for alerts
  defaultPriority: 5
  
  # Whether to send resolved alerts
  sendResolved: false
  
  # Additional labels to include in messages (optional)
  includeLabels: []
  # Example:
  # includeLabels:
  #   - job
  #   - environment
  #   - team

# Environment variables
env: []

# Probes configuration
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
