apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafananotificationtemplates.monitoring.zengarden.space
spec:
  group: monitoring.zengarden.space
  names:
    kind: GrafanaNotificationTemplate
    listKind: GrafanaNotificationTemplateList
    plural: grafananotificationtemplates
    singular: grafananotificationtemplate
    shortNames:
      - gnt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - grafanaRef
                - name
                - template
              properties:
                grafanaRef:
                  type: object
                  required:
                    - secretRef
                  properties:
                    secretRef:
                      type: object
                      required:
                        - name
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        key:
                          type: string
                          default: token
                name:
                  type: string
                  description: Template name
                template:
                  type: string
                  description: Go template content
            status:
              type: object
              properties:
                version:
                  type: integer
                  description: Version for optimistic concurrency control
                lastSynced:
                  type: string
                  format: date-time
                syncStatus:
                  type: string
                  enum:
                    - Synced
                    - Failed
                    - Pending
                message:
                  type: string
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: .spec.name
        - name: Status
          type: string
          jsonPath: .status.syncStatus
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
