apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanamutetimings.monitoring.zengarden.space
spec:
  group: monitoring.zengarden.space
  names:
    kind: GrafanaMuteTiming
    listKind: GrafanaMuteTimingList
    plural: grafanamutetimings
    singular: grafanamutetiming
    shortNames:
      - gmt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - grafanaRef
                - name
                - timeIntervals
              properties:
                grafanaRef:
                  type: object
                  required:
                    - secretRef
                  properties:
                    secretRef:
                      type: object
                      required:
                        - name
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        key:
                          type: string
                          default: token
                name:
                  type: string
                  description: Mute timing name
                timeIntervals:
                  type: array
                  description: Time interval definitions
                  items:
                    type: object
                    properties:
                      times:
                        type: array
                        items:
                          type: object
                          required:
                            - startTime
                            - endTime
                          properties:
                            startTime:
                              type: string
                              description: Start time in HH:MM format
                            endTime:
                              type: string
                              description: End time in HH:MM format
                      weekdays:
                        type: array
                        items:
                          type: string
                        description: Days of week (monday, tuesday, etc.)
                      daysOfMonth:
                        type: array
                        items:
                          type: string
                        description: Days of month (1-31, -1 for last day)
                      months:
                        type: array
                        items:
                          type: string
                        description: Months (1-12 or january, february, etc.)
                      years:
                        type: array
                        items:
                          type: string
                        description: Years (2024, 2025, etc.)
            status:
              type: object
              properties:
                version:
                  type: integer
                  description: Version for optimistic concurrency control
                lastSynced:
                  type: string
                  format: date-time
                syncStatus:
                  type: string
                  enum:
                    - Synced
                    - Failed
                    - Pending
                message:
                  type: string
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: .spec.name
        - name: Status
          type: string
          jsonPath: .status.syncStatus
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
