apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.zengarden.space
spec:
  group: zengarden.space
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - email
                - roles
              properties:
                email:
                  type: string
                  description: "User email (matches OIDC identity)"
                  pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
                roles:
                  type: array
                  description: "List of roles assigned to the user"
                  items:
                    type: string
                    enum:
                      - app-developer
                      - platform-operator
                      - system-admin
                  minItems: 1
                enabled:
                  type: boolean
                  description: "Whether the user is active (default: true)"
                  default: true
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                roleBindings:
                  type: object
                  description: "Map of namespace to list of RoleBindings created"
                  additionalProperties:
                    type: array
                    items:
                      type: string
                lastUpdated:
                  type: string
                  format: date-time
                  description: "Timestamp of last reconciliation"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Email
          type: string
          jsonPath: .spec.email
        - name: Roles
          type: string
          jsonPath: .spec.roles
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
      - usr
