{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.serviceAccountName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "service.fullname" . }}-job-watcher
  labels:
    {{- include "service.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "service.fullname" . }}-job-watcher
  labels:
    {{- include "service.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "service.fullname" . }}-job-watcher
  apiGroup: rbac.authorization.k8s.io
{{- end }}
