apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gitea-automation.fullname" . }}-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea-automation.labels" . | nindent 4 }}
    app.kubernetes.io/component: org-creator
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "gitea-automation.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: jq-copy
        image: "ghcr.io/jqlang/jq:1.8.0"
        command: ['cp', '/usr/local/bin/jq', '/shared/jq']
        volumeMounts:
        - name: shared-tools
          mountPath: /shared
        securityContext:
          {{- toYaml .Values.job.securityContext | nindent 10 }}
      containers:
      - name: sync
        image: "alpine/curl:8.10.1"
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        command: ['/bin/sh']
        args: ['/scripts/sync.sh']
        env:
        - name: ORG_NAME
          value: {{ .Values.organization.name | quote }}
        - name: ORG_DESCRIPTION
          value: {{ .Values.organization.description | quote }}
        - name: ORG_WEBSITE
          value: {{ .Values.organization.website | quote }}
        - name: ORG_VISIBILITY
          value: {{ .Values.organization.visibility | quote }}
        - name: GITEA_SERVICE_NAME
          value: {{ .Values.gitea.service.name | quote }}
        - name: GITEA_NAMESPACE
          value: {{ .Values.gitea.service.namespace | quote }}
        - name: GITEA_SERVICE_PORT
          value: {{ .Values.gitea.service.port | quote }}
        - name: GITEA_ADMIN_USERNAME
          value: {{ .Values.gitea.admin.username | quote }}
        - name: GITEA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "gitea-automation.fullname" . }}-admin
              key: password
        - name: GITEA_TOKEN
          valueFrom:
            secretKeyRef:
              name: org-creator
              key: token
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "gitea-automation.fullname" . }}-github
              key: token
        - name: GITHUB_ORG
          value: {{ .Values.github.organization | quote }}
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
          readOnly: true
        - name: shared-tools
          mountPath: /shared
          readOnly: true
        securityContext:
          {{- toYaml .Values.job.securityContext | nindent 10 }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: script-volume
        configMap:
          name: {{ include "gitea-automation.fullname" . }}-script
          defaultMode: 0755
      - name: shared-tools
        emptyDir: {}
