apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea-automation.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea-automation.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.gitea.admin.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea-automation.fullname" . }}-github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea-automation.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.github.token | b64enc }}
