apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-action-runner-config
data:
  config.yaml: |-
    runner:
      capacity: 1
    cache:
      enabled: true
      external_server: "http://gitea-action-runner-cache/"
    container:
      privileged: true
      workdir_parent: /data/workspace
    host:
      workdir_parent: /data/act