apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: internal-ca-bundle
spec:
  sources:
    - useDefaultCAs: true
    - configMap:
        name: "internal-ca-tls"
        key: "ca.crt"
  target:
    configMap:
      key: "ca.crt"
    secret:
      key: "ca.crt"
    additionalFormats:
      pkcs12:
        key: "ca.p12"
