apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rotation-job
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
