apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rotation-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rotation-job
subjects:
  - kind: ServiceAccount
    name: rotation-job
