apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: integrations
    kind: ClusterSecretStore
  target:
    name: mikrotik-credentials
    creationPolicy: Owner
    template:
      data:
        MIKROTIK_BASEURL: "{{ .baseUrl }}"
        MIKROTIK_USERNAME: "{{ .username }}"
        MIKROTIK_PASSWORD: "{{ .password }}"
        MIKROTIK_SKIP_TLS_VERIFY: "false"
  data:
    - secretKey: baseUrl
      remoteRef:
        key: mikrotik-credentials
        property: baseUrl
    - secretKey: username
      remoteRef:
        key: mikrotik-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: mikrotik-credentials
        property: password