operator:
  replicaCount: 1
  image:
    repository: flant/shell-operator
    tag: v1.4.11
    pullPolicy: IfNotPresent
  logLevel: info
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 64535
    runAsGroup: 64535
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

pythonSidecar:
  image:
    repository: python
    tag: 3.12-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

serviceAccount:
  create: true
  name: rbac-operator

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 64535
  runAsGroup: 64535
  fsGroup: 64535
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}
tolerations: []
affinity: {}
