---
# ClusterRole for System Administrators
# Full access to system, platform, and application resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homelab:system-admin
  annotations:
    zengarden.space/role: system-admin
    zengarden.space/namespaces: "@argocd,argocd,gitea,metabase,victoria-metrics,cert-manager,secrets-system,metallb-system,ingress-nginx,external-dns,external-tunnel,cnpg-system,cilium-secrets,integrations,secrets"
rules:
  # Full access to all namespaced resources
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

  # Can view and manage cluster-scoped resources (except critical ones)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["namespaces", "nodes", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  # Cert-manager resources
  - apiGroups: ["cert-manager.io"]
    resources: ["*"]
    verbs: ["*"]

  # External Secrets Operator
  - apiGroups: ["external-secrets.io"]
    resources: ["*"]
    verbs: ["*"]

  # CNPG (CloudNativePG)
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["*"]
    verbs: ["*"]

  # MetalLB
  - apiGroups: ["metallb.io"]
    resources: ["*"]
    verbs: ["*"]

  # Cilium Network Policies
  - apiGroups: ["cilium.io"]
    resources: ["*"]
    verbs: ["*"]
