# Default values for karma-config
networkPolicy:
  enabled: true
  ingress:
    # Allow monitoring/metrics scraping
    allowMonitoring: true
    # Extra ingress rules
    extraRules: []
  egress:
    # Extra egress rules
    extraRules: []

# Configuration for Karma
config:
  # Port that karma runs on
  port: 8080
