apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-alert-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-alert-operator.labels" . | nindent 4 }}
