---
# Example: Application Developer
apiVersion: zengarden.space/v1
kind: User
metadata:
  name: dev-user
spec:
  email: developer@example.com
  roles:
    - app-developer
  enabled: true

---
# Example: Platform Operator
apiVersion: zengarden.space/v1
kind: User
metadata:
  name: platform-user
spec:
  email: platform@example.com
  roles:
    - platform-operator
  enabled: true

---
# Example: System Administrator
apiVersion: zengarden.space/v1
kind: User
metadata:
  name: admin-user
spec:
  email: admin@example.com
  roles:
    - system-admin
  enabled: true

---
# Example: Multiple Roles
apiVersion: zengarden.space/v1
kind: User
metadata:
  name: super-user
spec:
  email: super@example.com
  roles:
    - app-developer
    - platform-operator
    - system-admin
  enabled: true

---
# Example: Disabled User
apiVersion: zengarden.space/v1
kind: User
metadata:
  name: disabled-user
spec:
  email: disabled@example.com
  roles:
    - app-developer
  enabled: false
