---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-token-generator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-token-generator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-token-generator
subjects:
- kind: ServiceAccount
  name: gitea-token-generator
roleRef:
  kind: Role
  name: gitea-token-generator
  apiGroup: rbac.authorization.k8s.io
