apiVersion: v1
kind: Service
metadata:
  name: gitea-action-runner-cache
  namespace: gitea
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: gitea-action-runner-cache