apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gitea-action-runner
  name: gitea-action-runner
  namespace: gitea
spec:
  replicas: 4
  serviceName: gitea-action-runner
  selector:
    matchLabels:
      app: gitea-action-runner
  template:
    metadata:
      labels:
        app: gitea-action-runner
    spec:
      volumes:
      - name: docker-certs
        emptyDir: {}
      - name: docker-sock
        emptyDir: {}
      - name: runner-config
        configMap:
          name: gitea-action-runner-config
      containers:
      - name: runner
        image: gitea/act_runner:0.2.11
        command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- /opt/act/run.sh"]
        imagePullPolicy: Always
        env:
        - name: CONFIG_FILE
          value: /config/config.yaml
        - name: GITEA_INSTANCE_URL
          value: https://gitea.zengarden.space/
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-action-runner
              key: token
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run
        - name: docker-certs
          mountPath: /certs
        - name: runner-data
          mountPath: /data
        - name: runner-config
          mountPath: /config
      - name: daemon
        image: docker:23.0.6-dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run
        - name: docker-certs
          mountPath: /certs
  volumeClaimTemplates:
    - metadata:
        name: runner-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi