apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitea-automation.fullname" . }}-oauth-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea-automation.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth-setup
data:
  package.json: |
    {
      "name": "gitea-oauth-setup",
      "version": "1.0.0",
      "description": "Automated Gitea Google OAuth configuration",
      "main": "setup-google-oauth.js",
      "dependencies": {
        "playwright": "1.40.0"
      }
    }
  setup-google-oauth.js: |
{{ .Files.Get "files/setup-google-oauth.js" | indent 4 }}
