apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kubernetes.zengarden.spacee
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 6443
    targetPort: 6443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kubernetes
  namespace: kube-system
  labels:
    kubernetes.io/service-name: kubernetes
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 6443
endpoints:
  - addresses:
      - "192.168.88.170"
  - addresses:
      - "192.168.88.171"
  - addresses:
      - "192.168.88.172"
