# ArgoCD ApplicationSet configuration
applicationSet:
  name: applications
  namespace: argocd
  
  # Git repository configuration
  git:
    repoURL: https://gitea.zengarden.space/zengarden-space/manifests.git
    revision: main
    manifestsPath: "manifests/*"
  
  # Application template configuration
  template:
    project: default
    syncPolicy:
      automated:
        prune: true
        allowEmpty: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    
    # Destination cluster
    destinationServer: '{{.url}}'
