apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: secrets
      auth:
        serviceAccount:
          name: secrets
          namespace: secrets
      server:
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          key: "ca.crt"
          namespace: "kube-system"
