name: Cleanup CI Environment
description: Remove CI environment directory from manifests repository after PR is closed

inputs:
  slug:
    description: 'Environment slug (e.g., branch name) - will be hashed to create ENV_ID'
    required: true
  project-name:
    description: 'Project name'
    required: false
    default: ''
  component-type:
    description: 'Component type (apps, system, or platform)'
    required: false
    default: 'apps'
  cluster:
    description: 'Cluster name'
    required: false
    default: 'homelab'
  manifests-repo:
    description: 'Manifests repository (owner/repo)'
    required: false
    default: 'zengarden-space/manifests'
  token:
    description: 'GitHub/Gitea token with write access to manifests repo'
    required: true
  pr-number:
    description: 'Pull request number for commit message'
    required: false
    default: ''

outputs:
  environment-id:
    description: 'Environment identifier (sha256 hash of slug)'
    value: ${{ steps.env.outputs.id }}
  directory-removed:
    description: 'Whether the directory was found and removed (true/false)'
    value: ${{ steps.cleanup.outputs.removed }}

runs:
  using: composite
  steps:
    - name: Determine project name
      id: project
      shell: bash
      run: |
        if [ -n "${{ inputs.project-name }}" ]; then
          project_name="${{ inputs.project-name }}"
        else
          project_name=$(echo ${{ github.repository }} | cut -d'/' -f2)
        fi
        echo "name=$project_name" >> $GITHUB_OUTPUT
        echo "Project name: $project_name"

    - name: Calculate environment ID
      id: env
      shell: bash
      run: |
        slug="${{ inputs.slug }}"
        env_id=$(echo -n "$slug" | sha256sum | cut -c1-8)
        echo "id=$env_id" >> $GITHUB_OUTPUT
        echo "Slug: $slug"
        echo "Environment ID: $env_id"

    - name: Checkout manifests repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.manifests-repo }}
        ref: 'main'
        path: manifests-repo
        token: ${{ inputs.token }}
        fetch-depth: 0

    - name: Remove CI environment directory
      id: cleanup
      shell: bash
      run: |
        cd manifests-repo
        project_name="${{ steps.project.outputs.name }}"
        env_id="${{ steps.env.outputs.id }}"
        env_dir="${{ inputs.cluster }}/${{ inputs.component-type }}/ci-${env_id}/${project_name}"

        echo "Looking for directory: $env_dir"

        if [ -d "$env_dir" ]; then
          git rm -rf "$env_dir"
          git config user.name "Gitea Actions Bot"
          git config user.email "gitea-actions[bot]@users.noreply.zengarden.space"

          # Build commit message
          if [ -n "${{ inputs.pr-number }}" ]; then
            commit_msg="Cleanup CI environment ci-${env_id} after PR #${{ inputs.pr-number }} closed"
          else
            commit_msg="Cleanup CI environment ci-${env_id} for $project_name"
          fi

          git commit -m "$commit_msg"
          git push

          echo "removed=true" >> $GITHUB_OUTPUT
          echo "Successfully removed environment directory: $env_dir"
        else
          echo "removed=false" >> $GITHUB_OUTPUT
          echo "Environment directory not found: $env_dir"
          echo "Note: This is expected if the environment was already cleaned up or never created"
        fi
