apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "derived-secret-operator.fullname" . }}-hooks
  labels:
    {{- include "derived-secret-operator.labels" . | nindent 4 }}
data:
  derived-secret-handler.sh: {{ .Files.Get "files/derived-secret-handler.sh" | quote }}
