{{- if and (not .Values.masterPassword.existingSecret) .Values.masterPassword.value }}
apiVersion: v1
kind: Secret
metadata:
  name: master-password
  labels:
    {{- include "derived-secret-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-password: {{ .Values.masterPassword.value | quote }}
  canary-identifier: {{ .Values.masterPassword.canaryIdentifier | quote }}
{{- end }}
