apiVersion: v1
kind: Service
metadata:
  name: {{ include "derived-secret-operator.fullname" . }}
  labels:
    {{- include "derived-secret-operator.labels" . | nindent 4 }}
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    {{- include "derived-secret-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 9115
      targetPort: 9115
      protocol: TCP
