apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metabase-cnpg-operator.fullname" . }}-hooks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metabase-cnpg-operator.labels" . | nindent 4 }}
data:
  sync-cnpg-databases.sh: |
{{ .Files.Get "hooks/sync-cnpg-databases.sh" | indent 4 }}

