apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metabase-cnpg-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metabase-cnpg-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-email: {{ .Values.metabase.adminEmail | quote }}
  admin-password: {{ .Values.metabase.adminPassword | quote }}
