apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "metabase-cnpg-operator.fullname" . }}-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metabase-cnpg-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        {{- include "metabase-cnpg-operator.selectorLabels" . | nindent 8 }}
        job: metabase-setup
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: setup
        image: curlimages/curl:8.5.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        env:
        - name: METABASE_URL
          value: {{ .Values.metabase.url | quote }}
        - name: METABASE_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ include "metabase-cnpg-operator.fullname" . }}
              key: admin-email
        - name: METABASE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "metabase-cnpg-operator.fullname" . }}
              key: admin-password
        - name: METABASE_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "metabase-cnpg-operator.fullname" . }}
              key: google-client-id
        command:
        - /bin/sh
        - /scripts/setup-metabase.sh
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: scripts
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: scripts
        configMap:
          name: {{ include "metabase-cnpg-operator.fullname" . }}-scripts
          defaultMode: 0555
