apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vmsingle-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: server
      app.kubernetes.io/name: victoria-metrics-single
