apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: argocd-secret-generator
  labels:
    {{- include "argocd-config.labels" . | nindent 4 }}
spec:
  length: {{ .Values.secret.generator.length }}
  symbolCharacters: {{ .Values.secret.generator.symbols | quote }}
  noUpper: false
  noLower: false
  noDigits: false
  noSymbols: true
  allowRepeat: true
