apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager-gotify-nodejs.fullname" . }}
  labels:
    {{- include "alertmanager-gotify-nodejs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "alertmanager-gotify-nodejs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "alertmanager-gotify-nodejs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alertmanager-gotify-nodejs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: npm-install
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /app && npm install --production --silent
              echo "Dependencies installed successfully"
          volumeMounts:
            - name: app-code
              mountPath: /app
            - name: node-modules
              mountPath: /app/node_modules
          workingDir: /app
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /app && npm start
          ports:
            - name: http
              containerPort: {{ .Values.config.listenPort }}
              protocol: TCP
          env:
            - name: GOTIFY_MESSAGE_ENDPOINT
              value: {{ .Values.config.gotifyEndpoint | quote }}
            - name: GOTIFY_TOKEN
              value: {{ .Values.config.gotifyToken | quote }}
            - name: LISTEN_PORT
              value: {{ .Values.config.listenPort | quote }}
            - name: LISTEN_ADDR
              value: {{ .Values.config.listenAddr | quote }}
            - name: DEFAULT_PRIORITY
              value: {{ .Values.config.defaultPriority | quote }}
            - name: SEND_RESOLVED
              value: {{ .Values.config.sendResolved | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-code
              mountPath: /app
            - name: node-modules
              mountPath: /app/node_modules
          workingDir: /app
      volumes:
        - name: app-code
          configMap:
            name: {{ include "alertmanager-gotify-nodejs.fullname" . }}-app
        - name: node-modules
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
