{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: karma-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karma-config.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: karma
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress controllers
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              name: cert-manager
      ports:
        - protocol: TCP
          port: {{ .Values.config.port }}
    {{- if .Values.networkPolicy.ingress.allowMonitoring }}
    # Allow monitoring/metrics scraping
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vmselect
      ports:
        - protocol: TCP
          port: {{ .Values.config.port }}
    {{- end }}
    {{- with .Values.networkPolicy.ingress.extraRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow connection to AlertManager
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vmalertmanager
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: alertmanager
      ports:
        - protocol: TCP
          port: 9093
    # Allow HTTPS egress for external dependencies
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    {{- with .Values.networkPolicy.egress.extraRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
